export enum ConsumptionPointObjectType {
    APARTMENT = "APARTMENT",
    HOUSE_PERMANENTLY_INHABITED = "HOUSE_PERMANENTLY_INHABITED",
    HOUSE_OCCASIONALLY_INHABITED = "HOUSE_OCCASIONALLY_INHABITED",
    OTHER = "OTHER",
}