export enum EnergyContractTerminaion {
    //for DEFINITE notice period type
    CONTRACT_TERM_END_WITH_PRICE_INCREASE = "CONTRACT_TERM_END_WITH_PRICE_INCREASE",
    CONTRACT_TERM_END = "CONTRACT_TERM_END",
    PRICE_INCREASE_DURING_TERM = "PRICE_INCREASE_DURING_TERM",

    //for INDEFINITE notice period type
    PRICE_INCREASE = "PRICE_INCREASE",
    NOTICE_PERIOD_3_MONTHS = "NOTICE_PERIOD_3_MONTHS",
}