#resources:
#  pipelines:
#    - pipeline: mySourcePipeline
#      source: 'rixo-klappka-fe'
#      trigger:
#        branches:
#          - 'test-dependant-pipeline'

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: url
    values:
      - url1
      - url2
      - url3
      - url3
      - url3
      - url3
      - url5
  - name: all
    displayName: All
    type: boolean
    default: false

  - name: pwl
    displayName: Public wizard - life
    type: boolean
    default: false
  - name: pcwl
    displayName: Public client wizard - life
    type: boolean
    default: false

  - name: pwel
    displayName: Public wizard - electricity
    type: boolean
    default: false

  - name: poel
    displayName: Public order - electricity
    type: boolean
    default: false



variables:
  ENVIRONMENT: ${{ parameters.environment }}

trigger: none

pool: RixoUbuntuPool

name: v$(Date:yy.MM)$(Rev:.r)

stages:
  - stage: build
    displayName: E2E Testing
    jobs:
      - job: testing
        displayName: E2E Testing
        condition: and(succeeded(), ne(variables['Git.PullRequest'], True))
        steps:
          - checkout: self
            fetchDepth: 10
            persistCredentials: "true"
          - bash: yarn install
            displayName: "Prepare dependencies"
          - bash: |
              testFilesArray=()

              
              if [ ${{ parameters.pwl }} = True ] ; then
                  testFilesArray+=("**/insurance/life/**/*.cy.ts")
              fi
              if [ ${{ parameters.pcwl }} = True ] ; then
                  testFilesArray+=("**/insurance/life/**/*.client.cy.ts")
              fi
              
              
              
              if [ ${{ parameters.pwel }} = True ] ; then
                  testFilesArray+=("**/energy/electricity/**/*.client.cy.ts")
              fi

              
              
              if [ ${{ parameters.poel }} = True ] ; then
                  testFilesArray+=("**/energy/electricity/**/*.order.cy.ts")
              fi
              
              

              delim=""
              joined=""
              for item in "${testFilesArray[@]}"; do
                joined=$joined$delim\"$item\"
                delim=","
              done
              CYPRESS_BASE_URL=${ENVIRONMENT} yarn start:ci --config '{"specPattern":'[${joined}'],"pageLoadTimeout":180000}'
            displayName: "Testing"
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: "JUnit"
              testResultsFiles: "results/*.xml"
          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact: screenshots"
            condition: failed()
            continueOnError: True
            inputs:
              pathtoPublish: "$(Build.SourcesDirectory)/cypress/screenshots"
              ArtifactName: "screenshots"
